server:
  port: 9999
magic-api:
  #\u914D\u7F6Eweb\u9875\u9762\u5165\u53E3
  web: /magic/web
  resource:
    #\u914D\u7F6E\u6587\u4EF6\u5B58\u50A8\u4F4D\u7F6E\u3002\u5F53\u4EE5classpath\u5F00\u5934\u65F6\uFF0C\u4E3A\u53EA\u8BFB\u6A21\u5F0F
    location: /root/magic-api

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/magic-api-test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://47.93.15.59:4406/magic-api-test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 940116
